/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef DenBrowserAttest_h__
#define DenBrowserAttest_h__

#include "nscore.h"
#include "mozilla/Span.h"
#include "nsStringFwd.h"

class nsIInputStream;
class nsIURI;
namespace mozilla::net {
class nsHttpRequestHead;
}

namespace denbrowser {

/**
 * AddAttestHeaders — inject X-DenBrowser-Ts, X-DenBrowser-Nonce, and X-DenBrowser-Token
 * into aHead for an outbound HTTP/HTTPS request bound for a configured
 * attestation proxy.
 *
 * Called from nsHttpChannel::SetupChannelForTransaction().  The token is an
 * ECIES-encrypted payload that decrypts (using the matching private key held
 * by the attestation proxy) to a canonical plaintext that binds the request
 * to its method, host, path, and body hash.  A captured token cannot be
 * replayed against a different request because every field is in the
 * authenticated plaintext, and the per-request nonce is rejected by the
 * proxy's replay cache on the second use.
 *
 * Protocol:  ECIES with EC P-256, ANSI X9.63 KDF (SHA-256), AES-128-GCM.
 *
 * Canonical plaintext (v2):
 *   "denbrowser-attest:v2\n<nonce_b64>\n<ts>\n<host>\n<method>\n<path>\n<sha256_hex>"
 *
 * Proxy selection:
 *   A deployment may front several partner applications, each behind its own
 *   attestation proxy with its own keypair.  The build-time proxy table (see
 *   the DEN: PROXY_TABLE block in DenBrowserAttest.cpp, generated by build.sh
 *   from config/site-config.json) maps domains to proxies; the request is
 *   attested with the key of the entry claiming aURI's host.  A host no entry
 *   claims gets no headers at all — it is not proxied, so nothing on the other
 *   end could verify them.
 *
 * Key model:
 *   - Each attestation proxy holds its own EC P-256 private key.
 *   - The DenBrowser build embeds only the matching SPKI public keys.
 *   - A new keypair per browser release lets a proxy invalidate old builds
 *     by rotating its private key or removing the old public key from its
 *     allowlist.
 *
 * Behaviour when not configured:
 *   With an empty proxy table this function is a silent no-op.  No request is
 *   ever blocked by this code.
 *
 * aUploadLength is mReqContentLength after Firefox has normalized the upload
 * stream.  It is the full length used by the HTTP transaction; Available() is
 * deliberately not used because it only reports immediately readable bytes.
 *
 * Thread-safety:
 *   Public keys are imported from DER at most once per process and cached.
 *   Safe to call from any thread that can already call nsHttpChannel methods.
 */
nsresult AddAttestHeaders(mozilla::net::nsHttpRequestHead& aHead, nsIURI* aURI,
                          nsIInputStream* aUploadStream,
                          uint64_t aUploadLength);

/**
 * VerifyProxyPin — return false to abort a TLS handshake when the peer
 * claims to be one of our attestation proxies but presents the wrong public
 * key.
 *
 * Called from SSLServerCertVerification.cpp::AuthCertificateHook before any
 * application data flows.  The pins live in the same build-time proxy table
 * AddAttestHeaders() selects keys from, so each partner proxy is pinned to its
 * own TLS cert.  Behaviour:
 *
 *   - If `aHost` is claimed by no proxy entry, returns true — this function
 *     only constrains proxy hops, not other TLS connections.  An unconfigured
 *     build (empty table) therefore passes everything, and dev builds work
 *     normally.
 *   - If the matching entry has no pin configured, returns true.
 *   - Otherwise, decodes `aLeafCertDer`, computes sha256(SubjectPublicKeyInfo),
 *     and returns true iff it matches that entry's pin.
 *
 * On any decode/hash failure with a configured pin, returns false
 * (fail-closed: a broken cert isn't allowed to bypass the pin).
 */
bool VerifyProxyPin(const nsACString& aHost,
                    mozilla::Span<const uint8_t> aLeafCertDer);

}  // namespace denbrowser

#endif  // DenBrowserAttest_h__
